# Generated by Django 5.1.1 on 2024-09-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_department_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('discription', models.CharField(max_length=15)),
                ('date_field', models.CharField(max_length=15)),
            ],
        ),
    ]
